name: paylike_currencies
description: Covers all the currencies supported on paylike.io platform and provides a handy interface for them
version: 1.0.3
homepage: https://paylike.io
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
dev_dependencies:
  build_runner: ^2.1.2
  lints: ^1.0.0
  source_gen: ^1.1.1
  test: ^1.16.0
