name: paylike_currencies
description: Covers all the currencies supported on paylike.io platform
version: 1.0.0
homepage: https://paylike.io
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
