// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// CurrencyGenerator
// **************************************************************************

import 'package:paylike_currencies/paylike_currencies.dart';

enum CurrencyCode {
  AED,
  AFN,
  ALL,
  AMD,
  ANG,
  AOA,
  ARS,
  AUD,
  AWG,
  AZN,
  BAM,
  BBD,
  BDT,
  BGN,
  BHD,
  BIF,
  BMD,
  BND,
  BOB,
  BRL,
  BSD,
  BTN,
  BWP,
  BYR,
  BZD,
  CAD,
  CDF,
  CHF,
  CLP,
  CNY,
  COP,
  CRC,
  CUP,
  CVE,
  CZK,
  DJF,
  DKK,
  DOP,
  DZD,
  EGP,
  ERN,
  ETB,
  EUR,
  FJD,
  FKP,
  GBP,
  GEL,
  GHS,
  GIP,
  GMD,
  GNF,
  GTQ,
  GYD,
  HKD,
  HNL,
  HRK,
  HTG,
  HUF,
  IDR,
  ILS,
  INR,
  IQD,
  IRR,
  ISK,
  JMD,
  JOD,
  JPY,
  KES,
  KGS,
  KHR,
  KMF,
  KPW,
  KRW,
  KWD,
  KYD,
  KZT,
  LAK,
  LBP,
  LKR,
  LRD,
  LSL,
  MAD,
  MDL,
  MGA,
  MKD,
  MMK,
  MNT,
  MOP,
  MRU,
  MUR,
  MVR,
  MWK,
  MXN,
  MYR,
  MZN,
  NAD,
  NGN,
  NIO,
  NOK,
  NPR,
  NZD,
  OMR,
  PAB,
  PEN,
  PGK,
  PHP,
  PKR,
  PLN,
  PYG,
  QAR,
  RON,
  RSD,
  RUB,
  RWF,
  SAR,
  SBD,
  SCR,
  SDG,
  SEK,
  SGD,
  SHP,
  SLL,
  SOS,
  SRD,
  STN,
  SYP,
  SZL,
  THB,
  TJS,
  TMT,
  TND,
  TOP,
  TRY,
  TTD,
  TWD,
  TZS,
  UAH,
  UGX,
  USD,
  UYU,
  UZS,
  VES,
  VND,
  VUV,
  WST,
  XAF,
  XCD,
  XOF,
  XPF,
  YER,
  ZAR,
  ZMK,
  ZWL,
}

class PaylikeCurrencyCollection {
  static final Map<CurrencyCode, PaylikeCurrency> currencies = {
    CurrencyCode.AED:
        PaylikeCurrency('AED', 'United Arab Emirates dirham', 784, 2),
    CurrencyCode.AFN: PaylikeCurrency('AFN', 'Afghan afghani', 971, 2),
    CurrencyCode.ALL: PaylikeCurrency('ALL', 'Albanian lek', 8, 2),
    CurrencyCode.AMD: PaylikeCurrency('AMD', 'Armenian dram', 51, 2),
    CurrencyCode.ANG:
        PaylikeCurrency('ANG', 'Netherlands Antillean guilder', 532, 2),
    CurrencyCode.AOA: PaylikeCurrency('AOA', 'Angolan kwanza', 973, 2),
    CurrencyCode.ARS: PaylikeCurrency('ARS', 'Argentine peso', 32, 2),
    CurrencyCode.AUD: PaylikeCurrency('AUD', 'Australian dollar', 36, 2),
    CurrencyCode.AWG: PaylikeCurrency('AWG', 'Aruban florin', 533, 2),
    CurrencyCode.AZN: PaylikeCurrency('AZN', 'Azerbaijani manat', 944, 2),
    CurrencyCode.BAM: PaylikeCurrency(
        'BAM', 'Bosnia and Herzegovina convertible mark', 977, 2),
    CurrencyCode.BBD: PaylikeCurrency('BBD', 'Barbados dollar', 52, 2),
    CurrencyCode.BDT: PaylikeCurrency('BDT', 'Bangladeshi taka', 50, 2),
    CurrencyCode.BGN: PaylikeCurrency('BGN', 'Bulgarian lev', 975, 2),
    CurrencyCode.BHD: PaylikeCurrency('BHD', 'Bahraini dinar', 48, 3),
    CurrencyCode.BIF: PaylikeCurrency('BIF', 'Burundian franc', 108, 0),
    CurrencyCode.BMD: PaylikeCurrency('BMD', 'Bermudian dollar', 60, 2),
    CurrencyCode.BND: PaylikeCurrency('BND', 'Brunei dollar', 96, 2),
    CurrencyCode.BOB: PaylikeCurrency('BOB', 'Boliviano', 68, 2),
    CurrencyCode.BRL: PaylikeCurrency('BRL', 'Brazilian real', 986, 2),
    CurrencyCode.BSD: PaylikeCurrency('BSD', 'Bahamian dollar', 44, 2),
    CurrencyCode.BTN: PaylikeCurrency('BTN', 'Bhutanese ngultrum', 64, 2),
    CurrencyCode.BWP: PaylikeCurrency('BWP', 'Botswana pula', 72, 2),
    CurrencyCode.BYR: PaylikeCurrency('BYR', 'Belarusian ruble', 974, 0),
    CurrencyCode.BZD: PaylikeCurrency('BZD', 'Belize dollar', 84, 2),
    CurrencyCode.CAD: PaylikeCurrency('CAD', 'Canadian dollar', 124, 2),
    CurrencyCode.CDF: PaylikeCurrency('CDF', 'Congolese franc', 976, 2),
    CurrencyCode.CHF: PaylikeCurrency('CHF', 'Swiss franc', 756, 2),
    CurrencyCode.CLP: PaylikeCurrency('CLP', 'Chilean peso', 152, 0),
    CurrencyCode.CNY: PaylikeCurrency('CNY', 'Chinese yuan', 156, 2),
    CurrencyCode.COP: PaylikeCurrency('COP', 'Colombian peso', 170, 2),
    CurrencyCode.CRC: PaylikeCurrency('CRC', 'Costa Rican colon', 188, 2),
    CurrencyCode.CUP: PaylikeCurrency('CUP', 'Cuban peso', 192, 2),
    CurrencyCode.CVE: PaylikeCurrency('CVE', 'Cape Verde escudo', 132, 2),
    CurrencyCode.CZK: PaylikeCurrency('CZK', 'Czech koruna', 203, 2),
    CurrencyCode.DJF: PaylikeCurrency('DJF', 'Djiboutian franc', 262, 0),
    CurrencyCode.DKK: PaylikeCurrency('DKK', 'Danish krone', 208, 2),
    CurrencyCode.DOP: PaylikeCurrency('DOP', 'Dominican peso', 214, 2),
    CurrencyCode.DZD: PaylikeCurrency('DZD', 'Algerian dinar', 12, 2),
    CurrencyCode.EGP: PaylikeCurrency('EGP', 'Egyptian pound', 818, 2),
    CurrencyCode.ERN: PaylikeCurrency('ERN', 'Eritrean nakfa', 232, 2),
    CurrencyCode.ETB: PaylikeCurrency('ETB', 'Ethiopian birr', 230, 2),
    CurrencyCode.EUR: PaylikeCurrency('EUR', 'Euro', 978, 2),
    CurrencyCode.FJD: PaylikeCurrency('FJD', 'Fiji dollar', 242, 2),
    CurrencyCode.FKP: PaylikeCurrency('FKP', 'Falkland Islands pound', 238, 2),
    CurrencyCode.GBP: PaylikeCurrency('GBP', 'Pound sterling', 826, 2),
    CurrencyCode.GEL: PaylikeCurrency('GEL', 'Georgian lari', 981, 2),
    CurrencyCode.GHS: PaylikeCurrency('GHS', 'Ghanaian cedi', 936, 2),
    CurrencyCode.GIP: PaylikeCurrency('GIP', 'Gibraltar pound', 292, 2),
    CurrencyCode.GMD: PaylikeCurrency('GMD', 'Gambian dalasi', 270, 2),
    CurrencyCode.GNF: PaylikeCurrency('GNF', 'Guinean franc', 324, 0),
    CurrencyCode.GTQ: PaylikeCurrency('GTQ', 'Guatemalan quetzal', 320, 2),
    CurrencyCode.GYD: PaylikeCurrency('GYD', 'Guyanese dollar', 328, 2),
    CurrencyCode.HKD: PaylikeCurrency('HKD', 'Hong Kong dollar', 344, 2),
    CurrencyCode.HNL: PaylikeCurrency('HNL', 'Honduran lempira', 340, 2),
    CurrencyCode.HRK: PaylikeCurrency('HRK', 'Croatian kuna', 191, 2),
    CurrencyCode.HTG: PaylikeCurrency('HTG', 'Haitian gourde', 332, 2),
    CurrencyCode.HUF: PaylikeCurrency('HUF', 'Hungarian forint', 348, 2),
    CurrencyCode.IDR: PaylikeCurrency('IDR', 'Indonesian rupiah', 360, 2),
    CurrencyCode.ILS: PaylikeCurrency('ILS', 'Israeli new shekel', 376, 2),
    CurrencyCode.INR: PaylikeCurrency('INR', 'Indian rupee', 356, 2),
    CurrencyCode.IQD: PaylikeCurrency('IQD', 'Iraqi dinar', 368, 3),
    CurrencyCode.IRR: PaylikeCurrency('IRR', 'Iranian rial', 364, 2),
    CurrencyCode.ISK: PaylikeCurrency('ISK', 'Icelandic króna', 352, 2),
    CurrencyCode.JMD: PaylikeCurrency('JMD', 'Jamaican dollar', 388, 2),
    CurrencyCode.JOD: PaylikeCurrency('JOD', 'Jordanian dinar', 400, 3),
    CurrencyCode.JPY: PaylikeCurrency('JPY', 'Japanese yen', 392, 0),
    CurrencyCode.KES: PaylikeCurrency('KES', 'Kenyan shilling', 404, 2),
    CurrencyCode.KGS: PaylikeCurrency('KGS', 'Kyrgyzstani som', 417, 2),
    CurrencyCode.KHR: PaylikeCurrency('KHR', 'Cambodian riel', 116, 2),
    CurrencyCode.KMF: PaylikeCurrency('KMF', 'Comoro franc', 174, 0),
    CurrencyCode.KPW: PaylikeCurrency('KPW', 'North Korean won', 408, 2),
    CurrencyCode.KRW: PaylikeCurrency('KRW', 'South Korean won', 410, 0),
    CurrencyCode.KWD: PaylikeCurrency('KWD', 'Kuwaiti dinar', 414, 3),
    CurrencyCode.KYD: PaylikeCurrency('KYD', 'Cayman Islands dollar', 136, 2),
    CurrencyCode.KZT: PaylikeCurrency('KZT', 'Kazakhstani tenge', 398, 2),
    CurrencyCode.LAK: PaylikeCurrency('LAK', 'Lao kip', 418, 2),
    CurrencyCode.LBP: PaylikeCurrency('LBP', 'Lebanese pound', 422, 2),
    CurrencyCode.LKR: PaylikeCurrency('LKR', 'Sri Lankan rupee', 144, 2),
    CurrencyCode.LRD: PaylikeCurrency('LRD', 'Liberian dollar', 430, 2),
    CurrencyCode.LSL: PaylikeCurrency('LSL', 'Lesotho loti', 426, 2),
    CurrencyCode.MAD: PaylikeCurrency('MAD', 'Moroccan dirham', 504, 2),
    CurrencyCode.MDL: PaylikeCurrency('MDL', 'Moldovan leu', 498, 2),
    CurrencyCode.MGA: PaylikeCurrency('MGA', 'Malagasy ariary', 969, 2),
    CurrencyCode.MKD: PaylikeCurrency('MKD', 'Macedonian denar', 807, 2),
    CurrencyCode.MMK: PaylikeCurrency('MMK', 'Myanmar kyat', 104, 2),
    CurrencyCode.MNT: PaylikeCurrency('MNT', 'Mongolian tögrög', 496, 2),
    CurrencyCode.MOP: PaylikeCurrency('MOP', 'Macanese pataca', 446, 2),
    CurrencyCode.MRU: PaylikeCurrency('MRU', 'Mauritanian ouguiya', 929, 2),
    CurrencyCode.MUR: PaylikeCurrency('MUR', 'Mauritian rupee', 480, 2),
    CurrencyCode.MVR: PaylikeCurrency('MVR', 'Maldivian rufiyaa', 462, 2),
    CurrencyCode.MWK: PaylikeCurrency('MWK', 'Malawian kwacha', 454, 2),
    CurrencyCode.MXN: PaylikeCurrency('MXN', 'Mexican peso', 484, 2),
    CurrencyCode.MYR: PaylikeCurrency('MYR', 'Malaysian ringgit', 458, 2),
    CurrencyCode.MZN: PaylikeCurrency('MZN', 'Mozambican metical', 943, 2),
    CurrencyCode.NAD: PaylikeCurrency('NAD', 'Namibian dollar', 516, 2),
    CurrencyCode.NGN: PaylikeCurrency('NGN', 'Nigerian naira', 566, 2),
    CurrencyCode.NIO: PaylikeCurrency('NIO', 'Nicaraguan córdoba', 558, 2),
    CurrencyCode.NOK: PaylikeCurrency('NOK', 'Norwegian krone', 578, 2),
    CurrencyCode.NPR: PaylikeCurrency('NPR', 'Nepalese rupee', 524, 2),
    CurrencyCode.NZD: PaylikeCurrency('NZD', 'New Zealand dollar', 554, 2),
    CurrencyCode.OMR: PaylikeCurrency('OMR', 'Omani rial', 512, 3),
    CurrencyCode.PAB: PaylikeCurrency('PAB', 'Panamanian balboa', 590, 2),
    CurrencyCode.PEN: PaylikeCurrency('PEN', 'Peruvian Sol', 604, 2),
    CurrencyCode.PGK: PaylikeCurrency('PGK', 'Papua New Guinean kina', 598, 2),
    CurrencyCode.PHP: PaylikeCurrency('PHP', 'Philippine peso', 608, 2),
    CurrencyCode.PKR: PaylikeCurrency('PKR', 'Pakistani rupee', 586, 2),
    CurrencyCode.PLN: PaylikeCurrency('PLN', 'Polish złoty', 985, 2),
    CurrencyCode.PYG: PaylikeCurrency('PYG', 'Paraguayan guaraní', 600, 0),
    CurrencyCode.QAR: PaylikeCurrency('QAR', 'Qatari riyal', 634, 2),
    CurrencyCode.RON: PaylikeCurrency('RON', 'Romanian leu', 946, 2),
    CurrencyCode.RSD: PaylikeCurrency('RSD', 'Serbian dinar', 941, 2),
    CurrencyCode.RUB: PaylikeCurrency('RUB', 'Russian ruble', 643, 2),
    CurrencyCode.RWF: PaylikeCurrency('RWF', 'Rwandan franc', 646, 0),
    CurrencyCode.SAR: PaylikeCurrency('SAR', 'Saudi riyal', 682, 2),
    CurrencyCode.SBD: PaylikeCurrency('SBD', 'Solomon Islands dollar', 90, 2),
    CurrencyCode.SCR: PaylikeCurrency('SCR', 'Seychelles rupee', 690, 2),
    CurrencyCode.SDG: PaylikeCurrency('SDG', 'Sudanese pound', 938, 2),
    CurrencyCode.SEK: PaylikeCurrency('SEK', 'Swedish krona', 752, 2),
    CurrencyCode.SGD: PaylikeCurrency('SGD', 'Singapore dollar', 702, 2),
    CurrencyCode.SHP: PaylikeCurrency('SHP', 'Saint Helena pound', 654, 2),
    CurrencyCode.SLL: PaylikeCurrency('SLL', 'Sierra Leonean leone', 694, 2),
    CurrencyCode.SOS: PaylikeCurrency('SOS', 'Somali shilling', 706, 2),
    CurrencyCode.SRD: PaylikeCurrency('SRD', 'Surinamese dollar', 968, 2),
    CurrencyCode.STN:
        PaylikeCurrency('STN', 'São Tomé and Príncipe dobra', 930, 2),
    CurrencyCode.SYP: PaylikeCurrency('SYP', 'Syrian pound', 760, 2),
    CurrencyCode.SZL: PaylikeCurrency('SZL', 'Swazi lilangeni', 748, 2),
    CurrencyCode.THB: PaylikeCurrency('THB', 'Thai baht', 764, 2),
    CurrencyCode.TJS: PaylikeCurrency('TJS', 'Tajikistani somoni', 972, 2),
    CurrencyCode.TMT: PaylikeCurrency('TMT', 'Turkmenistani manat', 934, 2),
    CurrencyCode.TND: PaylikeCurrency('TND', 'Tunisian dinar', 788, 3),
    CurrencyCode.TOP: PaylikeCurrency('TOP', 'Tongan paʻanga', 776, 2),
    CurrencyCode.TRY: PaylikeCurrency('TRY', 'Turkish lira', 949, 2),
    CurrencyCode.TTD:
        PaylikeCurrency('TTD', 'Trinidad and Tobago dollar', 780, 2),
    CurrencyCode.TWD: PaylikeCurrency('TWD', 'New Taiwan dollar', 901, 2),
    CurrencyCode.TZS: PaylikeCurrency('TZS', 'Tanzanian shilling', 834, 2),
    CurrencyCode.UAH: PaylikeCurrency('UAH', 'Ukrainian hryvnia', 980, 2),
    CurrencyCode.UGX: PaylikeCurrency('UGX', 'Ugandan shilling', 800, 0),
    CurrencyCode.USD: PaylikeCurrency('USD', 'United States dollar', 840, 2),
    CurrencyCode.UYU: PaylikeCurrency('UYU', 'Uruguayan peso', 858, 2),
    CurrencyCode.UZS: PaylikeCurrency('UZS', 'Uzbekistan som', 860, 2),
    CurrencyCode.VES:
        PaylikeCurrency('VES', 'Venezuelan bolívar soberano', 928, 2),
    CurrencyCode.VND: PaylikeCurrency('VND', 'Vietnamese dong', 704, 0),
    CurrencyCode.VUV: PaylikeCurrency('VUV', 'Vanuatu vatu', 548, 0),
    CurrencyCode.WST: PaylikeCurrency('WST', 'Samoan tala', 882, 2),
    CurrencyCode.XAF: PaylikeCurrency('XAF', 'CFA franc BEAC', 950, 0),
    CurrencyCode.XCD: PaylikeCurrency('XCD', 'East Caribbean dollar', 951, 2),
    CurrencyCode.XOF: PaylikeCurrency('XOF', 'CFA franc BCEAO', 952, 0),
    CurrencyCode.XPF: PaylikeCurrency('XPF', 'CFP franc', 953, 0),
    CurrencyCode.YER: PaylikeCurrency('YER', 'Yemeni rial', 886, 2),
    CurrencyCode.ZAR: PaylikeCurrency('ZAR', 'South African rand', 710, 2),
    CurrencyCode.ZMK: PaylikeCurrency('ZMK', 'Zambian kwacha', 894, 2),
    CurrencyCode.ZWL: PaylikeCurrency('ZWL', 'Zimbabwean dollar', 716, 2),
  };
}
